language: python
python: 2.6
env:
  - TOX_ENV=py26-1.4
  - TOX_ENV=py26-1.5
  - TOX_ENV=py26-1.6
  - TOX_ENV=py27-1.4
  - TOX_ENV=py27-1.5
  - TOX_ENV=py27-1.6
  - TOX_ENV=py27-1.7
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
